### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by zhtangsh** [nknorg/tuna#1]
hi there,

I'm seeking helps for the  problems while trying tuna on my local machine.
I build and setup server and client with following message
Server
```
root@kitten:~/tuna/server# ./server
2019/04/04 09:00:43 Subscribed to topic httpproxy successfully: b317b7f7c40782a6aef13cf79e503e6e0d3859d016dcc26c17cf5bcb0ed59da2
2019/04/04 09:00:43 Subscribed to topic moonlight successfully: 0d7f6af8a0cdbe28c4ebce982f74e641a786a95e79b62ed2e9845b6dec56675b
```
Client 
```
root@kitten:~/tuna/client# ./client
2019/04/04 09:01:18 Couldn't unmarshal metadata: invalid character '.' after top-level value
2019/04/04 09:01:18 Connected to TCP at 172.104.82.159:30004 from httpproxy.023ae19733cfe37fef9c5017bb8961f63cd0347fb0caa9da1eac8b121e1e38d89b
2019/04/04 09:01:18 Connected to TCP at 172.104.82.159:30004 from moonlight.023ae19733cfe37fef9c5017bb8961f63cd0347fb0caa9da1eac8b121e1e38d89b
2019/04/04 09:01:18 Connected to UDP at {172.104.82.159 30005 } from moonlight.023ae19733cfe37fef9c5017bb8961f63cd0347fb0caa9da1eac8b121e1e38d89b
```
Then I setup httpproxy on port 8888 on my browser and received this error on client.
```
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:03:33 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
```
Any suggestions on making it work?

**Comment by yilunzhang** [comment]
You can try to switch to last version (Mar 11).

**Comment by trueinsider** [comment]
That's probably because of a change I pushed 1 hour ago. It contains incompatible changes to metadata format, so old metadata couldn't be parsed.

**Comment by zhtangsh** [comment]
Thanks guys, I'll give it a try on commit 6611b907e23cbe070591d366276f642b58a23114

**Comment by zhtangsh** [comment]
Same error on dcb1297fea9747a9952c47d69cb640ddf13e65ea.
```
2019/04/04 09:12:11 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:12:11 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:12:11 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
2019/04/04 09:12:11 Couldn't accept connection: accept tcp [::]:8888: accept4: too many open files
```

**Comment by yilunzhang** [comment]
This is your computer's problem. Try to run `ulimit -n 1024` in the same terminal window before running

**Comment by zhtangsh** [comment]
Thanks man, errors are gone but I http proxy seems not working.
Assume client is on 172.104.82.159:8888, should following code work?
```
export http_proxy='http://172.104.82.159:8888'
curl www.google.com
```

**Comment by yilunzhang** [comment]
You should use 127.0.0.1:8888 on the same machine as client is running.
Also you shouldn't run server on the same machine as the public ip address will not be resolved. Since there are some server side running, you just need to use tuna client at the moment

**Comment by zhtangsh** [comment]
got it. thanks man

**Comment by zhtangsh** [comment]
1. I start a server on remote vps with `./server`
2. I start client on local machine with `./client`
3. I run script `export http_proxy='http://127.0.0.1:8888'&&curl www.google.com` on local machine
Now I got empty reply and this error on server.
```
 Couldn't connect to host 127.0.0.1:8888 with error: dial tcp 127.0.0.1:8888: connect: connection refused
```

**Comment by zhtangsh** [comment]
never mind, it accidentally worked.

**Comment by zhtangsh** [comment]
It's not working again..

**Comment by yilunzhang** [comment]
Let's do it one at a time. What about you don't run the tuna server side, but just tuna client side?

**Comment by zhtangsh** [comment]
It worked. I could see that my client connected to a remote server at 
`157.230.136.253:30004`

**Comment by yilunzhang** [comment]
Yes, that's the tuna server I'm running

**Comment by yilunzhang** [comment]
If there are multiple tuna server, currently a random one will be selected. So your tuna server side may not be working properly. Did you open port 30004 and 30005 on it?

**Comment by yilunzhang** [comment]
Oh I think I know. In order to provide proxy service, your tuna server side has to run a proxy software.

**Comment by zhtangsh** [comment]
Yes, port 30004 and 30005 opened

**Comment by yilunzhang** [comment]
tuna is just a tunnel, and the service needs to run separately.

**Comment by zhtangsh** [comment]
alright, and is that what moonlight for?

**Comment by zhtangsh** [comment]
Any suggestions on the proxy software?

**Comment by yilunzhang** [comment]
I use this one for proxy: https://github.com/elazarl/goproxy
Moonlight is this one: https://moonlight-stream.org

**Comment by zhtangsh** [comment]
Thanks a lot.
