### ISSUE TITLE
-entry --reverse - error: wrap conn error: EOF

### ISSUE THREAD

**Issue by MutsiMutsi** [nknorg/tuna#160]
Running tuna on windows server with command:
```
./tuna entry --reverse
```

yields the following logs:
``` c
./tuna entry --reverse
2024/04/19 14:05:28 Your NKN wallet address is: X
2024/04/19 14:05:29 Existing subscription expires after 39982 blocks
2024/04/19 14:05:55 wrap conn error: EOF
2024/04/19 14:06:25 Couldn't accept stream: EOF
2024/04/19 14:06:25 Couldn't receive data from local: read udp [::]:54211: use of closed network connection
2024/04/19 14:06:25 Error while closing: close tcp X:30020->183.252.110.129:21490: use of closed network connection
2024/04/19 14:08:27 wrap conn error: EOF
2024/04/19 14:10:47 wrap conn error: EOF
2024/04/19 14:10:57 bandwidth measurement server error: write tcp X:30020->218.17.136.68:45974: wsasend: An existing connection was forcibly closed by the remote host.
2024/04/19 14:11:15 wrap conn error: EOF
2024/04/19 14:11:19 bandwidth measurement server error: write tcp X:30020->218.17.136.68:46372: wsasend: An existing connection was forcibly closed by the remote host.
2024/04/19 14:11:37 wrap conn error: EOF
2024/04/19 14:13:20 wrap conn error: EOF
```

Port 30020 is open and available for TCP.

**Comment by yilunzhang** [comment]
If you want to use reverse proxy service you should run `tuna exit --reverse`. Entry and exit are defined by network flow so their role are opposite in forward and reverse mode:
In forward mode, entry is user, exit is service provider;
In reverse mode, entry is service provider, exit is user.

**Comment by MutsiMutsi** [comment]
@yilunzhang I followed the readme for : "How to become a TUNA service provider and earn NKN from it":
Entry Mode
The first way is to use the reverse mode of the entry to provide reverse proxy services

```./tuna -b=[YOUR_BENEFICIARY_ADDR] entry --reverse```

**Comment by yilunzhang** [comment]
Ah so you intended to become a service provider!

So the command you run is correct and the logs you saw are normal, it happens when something other than tuna tries to connect to your open port, like all those port scanner. They don't use tuna protocol and thus will cause error. But don't worry they won't affect anything, just gives you some log output showing their existence.
